# emacs/doom_cache/Containerfile

# Copyright (c) 2025 Tim Perkins

ARG EMACS_BUILDER_IMAGE="scratch"
FROM $EMACS_BUILDER_IMAGE AS emacs-builder
FROM ubuntu:22.04

# Ensure root user
USER root
WORKDIR /

# Make sure we don't get prompted
ARG DEBIAN_FRONTEND="noninteractive"
ARG TERM="dumb"

# Install necessary prerequisites
RUN apt-get update \
    && apt-get install -y \
        curl \
        git \
        gnupg \
    && rm -rf /var/lib/apt/lists/*

# Install Emacs by copying it
COPY --from=emacs-builder /usr/local /usr/local

# Install all the runtime dependencies
RUN apt-get update \
    && sed -e "s/[[:space:]]*#.*//" -e "/^[[:space:]]*$/d" \
        /usr/local/share/emacs/emacs_runtime_deps.txt \
        | xargs apt-get install -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Doom Emacs variables
ARG DE_REPO="https://github.com/hlissner/doom-emacs"
ARG DE_BRANCH="master"
ARG DE_HASH="1d7a94b96b4410a3747ec579c728a79413379e64"
ARG DE_EMACS_DIR="/vols/emacs.d"
ARG DE_DOOM_DIR="/vols/doom.d"

# Clone Doom to the Emacs config directory
RUN git clone --branch $DE_BRANCH --single-branch $DE_REPO $DE_EMACS_DIR \
    && cd $DE_EMACS_DIR \
    && git reset --hard $DE_HASH

# Add Doom executables to PATH
ENV PATH=$DE_EMACS_DIR/bin:$PATH

# Set environment variables used by Doom
ENV EMACSDIR=$DE_EMACS_DIR
ENV DOOMDIR=$DE_DOOM_DIR

# Initialize Doom config, enable VTerm, then do Doom install
RUN mkdir -p $DE_DOOM_DIR \
    && cp $DE_EMACS_DIR/static/init.example.el $DE_DOOM_DIR/init.el \
    && cp $DE_EMACS_DIR/static/config.example.el $DE_DOOM_DIR/config.el \
    && cp $DE_EMACS_DIR/static/packages.example.el $DE_DOOM_DIR/packages.el \
    && sed -e "s/[(]\?evil/;;&/" -e "s/;;\([(]\?vterm\)/\1/" -i $DE_DOOM_DIR/init.el \
    && doom install --force --verbose --no-config --no-env --no-hooks
