# emsdk/Containerfile

# Copyright (c) 2023 Tim Perkins

ARG BASE_IMAGE="scratch"
FROM $BASE_IMAGE

# Set shell to Bash with better error flags
SHELL ["/bin/bash", "-euo", "pipefail", "-c"]

# Ensure root user
USER root
WORKDIR /

# Make sure we don't get prompted
ARG DEBIAN_FRONTEND="noninteractive"
ARG TERM="dumb"

# Xpra variables
ARG XPRA_SOURCES_URL="https://raw.githubusercontent.com/Xpra-org/xpra/master/packaging/repos/jammy/xpra.sources"
ARG XPRA_SOURCES_FILE="/etc/apt/sources.list.d/xpra.sources"
ARG XPRA_KEY_URL="https://xpra.org/xpra.asc"
ARG XPRA_KEY_FILE="/usr/share/keyrings/xpra.asc"

# Add the Xpra repo
RUN curl -fL -o $XPRA_KEY_FILE "$XPRA_KEY_URL" \
    && curl -fL -o $XPRA_SOURCES_FILE "$XPRA_SOURCES_URL"

# Install Xpra and some recommended packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        dbus-x11 \
        python3-cryptography \
        python3-gi-cairo \
        python3-paramiko \
        python3-setproctitle \
        python3-xdg \
        xpra \
        xpra-audio \
        xpra-audio-server \
        xpra-codecs-extras \
        xpra-x11 \
        xterm \
    && rm -rf /var/lib/apt/lists/*

# Switch to non-root user
USER $DEV_USER
WORKDIR $DEV_USER_HOME
