# python/Containerfile

# Copyright (c) 2024 Tim Perkins

ARG BASE_IMAGE="scratch"
FROM $BASE_IMAGE

# Ensure root user
USER root
WORKDIR /

# Make sure we don't get prompted
ARG DEBIAN_FRONTEND="noninteractive"
ARG TERM="dumb"

# Don't cache while building the image
ARG PIP_NO_CACHE_DIR=1

# Don't complain about verison
ENV PIP_DISABLE_PIP_VERSION_CHECK=1

# Install basic Python packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        python-is-python3 \
        python3 \
        python3-pip \
        python3-pytest \
        python3-setuptools \
        python3-venv \
        python3-virtualenv \
        python3-wheel \
    && rm -rf /var/lib/apt/lists/*

# Upgrade Pip with Pip
RUN pip install --upgrade pip

# Install Pipx with Pip, so we can get version 1.6.0
RUN pip install --root-user-action ignore "pipx>=1.6.0"

# Install Poetry
RUN pipx install --global "poetry>=1.8.0"

# Install other essential tools
RUN pipx install --global \
        black \
        flake8 \
        isort \
        mypy \
        ruff \
        tox \
        uv

# Enable Poetry autocompletion
RUN poetry completions bash > $DEV_USER_HOME/.bashrc_poetry \
    && { \
        echo; \
        echo "# Source Poetry autocompletion"; \
        echo "source \"\$HOME/.bashrc_poetry\""; \
    } >> $DEV_USER_HOME/.bashrc

# Switch to non-root user
USER $DEV_USER
WORKDIR $DEV_USER_HOME
