# ros/Containerfile

# Copyright (c) 2024 Tim Perkins

ARG BASE_CONTAINER
FROM $BASE_CONTAINER

# Ensure root user
USER root
WORKDIR /

# Make sure we don't get prompted
ARG DEBIAN_FRONTEND="noninteractive"
ARG TERM="dumb"

# ROS variables
ARG ROS_DEB_ARCH="amd64"
ARG ROS_DEB_URL="http://packages.ros.org/ros2/ubuntu"
ARG ROS_DEB_DIST="jammy"
ARG ROS_DEB_COMP="main"
ARG ROS_KEY_URL="https://raw.githubusercontent.com/ros/rosdistro/master/ros.key"
ARG ROS_KEY_FILE="/usr/share/keyrings/ros-archive-keyring.gpg"

# Colcon variables
ARG COLCON_MIXIN_URL="https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml"
ARG COLCON_METADATA_URL="https://raw.githubusercontent.com/colcon/colcon-metadata-repository/master/index.yaml"

# Add ROS repo
RUN curl -fL -o $ROS_KEY_FILE "$ROS_KEY_URL" \
    && { \
        echo "# ROS Repo"; \
        echo "deb [arch=$ROS_DEB_ARCH signed-by=$ROS_KEY_FILE] $ROS_DEB_URL $ROS_DEB_DIST $ROS_DEB_COMP"; \
    } >> /etc/apt/sources.list.d/ros2.list

# Set ROS distro environment variable
ENV ROS_DISTRO="humble"

# Install ROS packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        'ros-humble-ros-base=0.10.0-1*' \
        python3-colcon-clean \
        python3-colcon-common-extensions \
        python3-colcon-mixin \
        python3-rosdep \
        python3-vcstool \
    && rm -rf /var/lib/apt/lists/*

# Install extra linters
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ros-humble-ament-cmake-clang-format \
        ros-humble-ament-cmake-clang-tidy \
    && rm -rf /var/lib/apt/lists/*

# Bootstrap Rosdep
RUN rosdep init

# Copy the ROS entry point
COPY ros_entrypoint.sh $ENTRYPOINT_DIR/20_ros_entrypoint.sh

# Switch to non-root user
USER $DEV_USER
WORKDIR $DEV_USER_HOME

# Update Rosdep
RUN rosdep update --rosdistro $ROS_DISTRO

# Setup Colcon mixin and metadata
RUN colcon --log-base /dev/null mixin add default "$COLCON_MIXIN_URL" \
    && colcon --log-base /dev/null mixin update \
    && colcon --log-base /dev/null metadata add default "$COLCON_METADATA_URL" \
    && colcon --log-base /dev/null metadata update

# Copy the extra bashrc for completion, etc
COPY bashrc_ros.bash $DEV_USER_HOME/.bashrc_ros

# Enable ROS autocompletion
RUN { \
        echo; \
        echo "# Source extra ROS shell helpers"; \
        echo "source \"\$HOME/.bashrc_ros\""; \
    } >> $DEV_USER_HOME/.bashrc

# Capture the MD5 sum used to ID the container
ARG ROS_CONTAINER_MD5SUM
ENV ROS_CONTAINER_MD5SUM=$ROS_CONTAINER_MD5SUM
