# misc/Containerfile

# Copyright (c) 2026 Tim Perkins

ARG BASE_IMAGE="scratch"
FROM $BASE_IMAGE

# Set shell to Bash with better error flags
SHELL ["/bin/bash", "-euo", "pipefail", "-c"]

# Ensure root user
USER root
WORKDIR /

# Make sure we don't get prompted
ARG DEBIAN_FRONTEND="noninteractive"
ARG TERM="dumb"

# Install any extra packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libqt5webengine5 \
    && rm -rf /var/lib/apt/lists/*

# Variables for Bazel
ARG BAZEL_VER="9.2.0"
ARG BAZEL_URL="https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VER/bazel-$BAZEL_VER-linux-x86_64"
ARG BAZEL_MD5SUM="4339221b8a9d6235353f218a4dc83add"
ARG BAZEL_FILE="/usr/local/bin/bazel"
ARG BAZEL_COMP_HEAD_URL="https://raw.githubusercontent.com/bazelbuild/bazel/$BAZEL_VER/scripts/bazel-complete-header.bash"
ARG BAZEL_COMP_TEMP_URL="https://raw.githubusercontent.com/bazelbuild/bazel/$BAZEL_VER/scripts/bazel-complete-template.bash"
ARG BAZEL_COMP_FILE="/etc/bash_completion.d/bazel"

# Install Bazel and enable Bash completion
RUN BAZEL_TMP=$(mktemp) \
    && BAZEL_COMP_TMP=$(mktemp) \
    && BAZEL_OUT_TMP=$(mktemp -d) \
    && curl -fsSL -o $BAZEL_TMP "$BAZEL_URL" \
    && (echo "$BAZEL_MD5SUM  $BAZEL_TMP" | md5sum --quiet -c -) \
    && install -m 755 $BAZEL_TMP $BAZEL_FILE \
    && curl -fsSL "$BAZEL_COMP_HEAD_URL" > $BAZEL_COMP_TMP \
    && $BAZEL_FILE --batch --output_user_root=$BAZEL_OUT_TMP help completion >> $BAZEL_COMP_TMP \
    && curl -fsSL "$BAZEL_COMP_TEMP_URL" >> $BAZEL_COMP_TMP \
    && { \
        echo '_bazelisk__complete() { local BAZEL=bazelisk; _bazel__complete "$@"; }'; \
        echo "complete -F _bazelisk__complete -o nospace bazelisk"; \
    } >> $BAZEL_COMP_TMP \
    && install -m 644 $BAZEL_COMP_TMP $BAZEL_COMP_FILE \
    && rm -rf $BAZEL_TMP $BAZEL_COMP_TMP $BAZEL_OUT_TMP

# Copy system Bazel config
COPY --chown=root bazel.bazelrc /etc/bazel.bazelrc

# Variables for Bazelisk
ARG BAZELISK_VER="1.29.0"
ARG BAZELISK_URL="https://github.com/bazelbuild/bazelisk/releases/download/v$BAZELISK_VER/bazelisk-linux-amd64"
ARG BAZELISK_MD5SUM="bf259781802f31e42aa6a31a7f61c218"
ARG BAZELISK_FILE="/usr/local/bin/bazelisk"

# Install Bazelisk (without masking Bazel)
RUN BAZELISK_TMP=$(mktemp) \
    && curl -fsSL -o $BAZELISK_TMP "$BAZELISK_URL" \
    && (echo "$BAZELISK_MD5SUM  $BAZELISK_TMP" | md5sum --quiet -c -) \
    && install -m 755 $BAZELISK_TMP $BAZELISK_FILE \
    && rm -f $BAZELISK_TMP

# Variables for prek
ARG PREK_VER="0.5.5"
ARG PREK_URL="https://github.com/j178/prek/releases/download/v$PREK_VER/prek-x86_64-unknown-linux-gnu.tar.gz"
ARG PREK_MD5SUM="1c75c6cfa0a53579823ebc679816f232"
ARG PREK_FILE="/usr/local/bin/prek"
ARG PREK_COMP_FILE="/etc/bash_completion.d/prek"

# Install prek and enable Bash completion
RUN PREK_TAR_TMP=$(mktemp) \
    && PREK_TMP=$(mktemp) \
    && curl -fsSL -o $PREK_TAR_TMP "$PREK_URL" \
    && (echo "$PREK_MD5SUM  $PREK_TAR_TMP" | md5sum --quiet -c -) \
    && tar -xzOf $PREK_TAR_TMP --wildcards '*/prek' > $PREK_TMP \
    && install -m 755 $PREK_TMP $PREK_FILE \
    && $PREK_FILE util generate-shell-completion bash > $PREK_COMP_FILE \
    && rm -f $PREK_TAR_TMP $PREK_TMP

# Variables for JFrog CLI
ARG JFROG_VER="2.126.0"
ARG JFROG_URL="https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/$JFROG_VER/jfrog-cli-linux-amd64/jf"
ARG JFROG_MD5SUM="cbecb8ffaeea675e063d2b6dffcd96ee"
ARG JFROG_FILE="/usr/local/bin/jf"
ARG JFROG_COMP_FILE="/etc/bash_completion.d/jf"

# Install JFrog CLI and enable Bash completion
RUN JFROG_TMP=$(mktemp) \
    && JFROG_HOME_TMP=$(mktemp -d) \
    && curl -fsSL -o $JFROG_TMP "$JFROG_URL" \
    && (echo "$JFROG_MD5SUM  $JFROG_TMP" | md5sum --quiet -c -) \
    && install -m 755 $JFROG_TMP $JFROG_FILE \
    && JFROG_CLI_HOME_DIR=$JFROG_HOME_TMP $JFROG_FILE completion bash > $JFROG_COMP_FILE \
    && rm -rf $JFROG_TMP $JFROG_HOME_TMP

# Create a link to put this in the "expected" place
RUN ln -s $JFROG_FILE $DEV_USER_HOME/.local/bin/jf \
    && chown -h $DEV_USER_UID:$DEV_USER_GID $DEV_USER_HOME/.local/bin/jf

# Variables for gcloud CLI
ARG GCLOUD_VER="588.0.0"
ARG GCLOUD_URL="https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-$GCLOUD_VER-linux-x86_64.tar.gz"
ARG GCLOUD_MD5SUM="f30011b5d4fbcd4e9c33cc6b453d7d56"
ARG GCLOUD_DIR="/opt/google-cloud-sdk"
ARG GCLOUD_FILE="/usr/local/bin/gcloud"
ARG GSUTIL_FILE="/usr/local/bin/gsutil"
ARG GCLOUD_COMP_FILE="/etc/bash_completion.d/gcloud"

# Install gcloud CLI (with gsutil) and enable Bash completion
RUN GCLOUD_TAR_TMP=$(mktemp) \
    && GCLOUD_CONFIG_TMP=$(mktemp -d) \
    && curl -fsSL -o $GCLOUD_TAR_TMP "$GCLOUD_URL" \
    && (echo "$GCLOUD_MD5SUM  $GCLOUD_TAR_TMP" | md5sum --quiet -c -) \
    && mkdir -p $GCLOUD_DIR \
    && tar -xzf $GCLOUD_TAR_TMP -C $GCLOUD_DIR --strip-components=1 \
    && ln -s $GCLOUD_DIR/bin/gcloud $GCLOUD_FILE \
    && ln -s $GCLOUD_DIR/bin/gsutil $GSUTIL_FILE \
    && export CLOUDSDK_CONFIG=$GCLOUD_CONFIG_TMP \
    && $GCLOUD_FILE config set --installation component_manager/disable_update_check true \
    && $GCLOUD_FILE config set --installation core/disable_usage_reporting true \
    && install -m 644 $GCLOUD_DIR/completion.bash.inc $GCLOUD_COMP_FILE \
    && rm -rf $GCLOUD_TAR_TMP $GCLOUD_CONFIG_TMP

# Switch to non-root user
USER $DEV_USER
WORKDIR $DEV_USER_HOME
