# cpp/Containerfile

# Copyright (c) 2024 Tim Perkins

ARG BASE_IMAGE="scratch"
FROM $BASE_IMAGE

# Ensure root user
USER root
WORKDIR /

# Make sure we don't get prompted
ARG DEBIAN_FRONTEND="noninteractive"
ARG TERM="dumb"

# Install the old clang tools, so we can override the symlinks. The problem
# is, if we don't do this, then install something that requires Clang as a
# dependency, installing the old Clang blows away the symlinks set up below.
# Ideally there would be a better way to do this, for example, installing custom
# Debian packages that set the correct symlinks.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        clang \
        lld \
        lldb \
        clang-format \
        clangd \
    && rm -rf /var/lib/apt/lists/*

# LLVM variables
ARG LLVM_DEB_URL="http://apt.llvm.org/jammy/"
ARG LLVM_DEB_DIST="llvm-toolchain-jammy-16"
ARG LLVM_DEB_COMP="main"
ARG LLVM_KEY_URL="https://apt.llvm.org/llvm-snapshot.gpg.key"
ARG LLVM_KEY_FILE="/usr/share/keyrings/llvm-keyring.gpg"

# Add LLVM repo
RUN curl -fL "$LLVM_KEY_URL" | gpg --dearmor > $LLVM_KEY_FILE \
    && { \
        echo "# LLVM Repo"; \
        echo "deb [signed-by=$LLVM_KEY_FILE] $LLVM_DEB_URL $LLVM_DEB_DIST $LLVM_DEB_COMP"; \
        echo "deb-src [signed-by=$LLVM_KEY_FILE] $LLVM_DEB_URL $LLVM_DEB_DIST $LLVM_DEB_COMP"; \
    } >> /etc/apt/sources.list.d/llvm.list

# Install Clang tools
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        clang-16 \
        lld-16 \
        lldb-16 \
        clang-format-16 \
        clangd-16 \
        llvm-16-dev \
        libclang-16-dev \
    && rm -rf /var/lib/apt/lists/*

# Make aliases for some Clang tools
RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-16 1000 \
    && update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-16 1000 \
    && update-alternatives --install /usr/bin/clang-cpp clang-cpp /usr/bin/clang-cpp-16 1000 \
    && update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/ld.lld-16 1000 \
    && update-alternatives --install /usr/bin/lldb lldb /usr/bin/lldb-16 1000 \
    && update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-16 1000 \
    && update-alternatives --install /usr/bin/clang-format-diff clang-format-diff /usr/bin/clang-format-diff-16 1000 \
    && update-alternatives --install /usr/bin/clangd clangd /usr/bin/clangd-16 1000

# Update common commands to use Clang by default. WARNING: DO NOT ATTEMPT TO USE
# CLANG FOR BUILDING THINGS LIKE KERNEL MODULES! THAT WON'T WORK! DON'T ATTEMPT
# TO UPDATE YOUR KERNEL AND USE DKMS! THAT WON'T WORK!
RUN update-alternatives --install /usr/bin/cc cc /usr/bin/clang 1000 \
    && update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 1000 \
    && update-alternatives --install /usr/bin/cpp cpp /usr/bin/clang-cpp 1000 \
    && update-alternatives --install /usr/bin/ld ld /usr/bin/ld.lld 1000

# Include What You Use Variables (v0.20 for use with LLVM 16)
ARG IWYU_TAR_URL="https://include-what-you-use.org/downloads/include-what-you-use-0.20.src.tar.gz"

# Install Include What You Use
RUN IWYU_TMP=$(mktemp -d) \
    && cd $IWYU_TMP \
    && curl -fL "$IWYU_TAR_URL" -o iwyu.tar.gz \
    && tar xf iwyu.tar.gz \
    && cd include-what-you-use \
    && cmake -DCMAKE_PREFIX_PATH=/usr/lib/llvm-16 -S . -B build \
    && cmake --build build \
    && cmake --build build --target install \
    && cp -t /usr/local/bin iwyu_tool.py fix_includes.py \
    && cd $WORKDIR \
    && rm -rf $IWYU_TMP

# Fix the IWYU resource directory, which is a required part of installation.
# See: https://github.com/include-what-you-use/include-what-you-use/issues/100
RUN CLANG_RES_DIR=$(clang -print-resource-dir) \
    && IWYU_RES_DIR=$(include-what-you-use -print-resource-dir || true) \
    && mkdir -p $(dirname $IWYU_RES_DIR) \
    && ln -s $CLANG_RES_DIR $IWYU_RES_DIR

# Switch to non-root user
USER $DEV_USER
WORKDIR $DEV_USER_HOME
