# emacs/Containerfile

# Copyright (c) 2023 Tim Perkins

ARG BASE_IMAGE="scratch"
ARG EMACS_BUILDER_IMAGE="scratch"
ARG DOOM_CACHE_IMAGE="scratch"
FROM $EMACS_BUILDER_IMAGE AS emacs-builder
FROM $DOOM_CACHE_IMAGE AS doom-cache
FROM $BASE_IMAGE

# Ensure root user
USER root
WORKDIR /

# Make sure we don't get prompted
ARG DEBIAN_FRONTEND="noninteractive"
ARG TERM="dumb"

# Install Emacs by copying it
COPY --from=emacs-builder /usr/local /usr/local

# Install all the runtime dependencies
RUN apt-get update \
    && sed -e "s/[[:space:]]*#.*//" -e "/^[[:space:]]*$/d" \
        /usr/local/share/emacs/emacs_runtime_deps.txt \
        | xargs apt-get install -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Install xorg for GUI, libtool-bin for building VTerm, libcanberra-gtk3-module
# to silence warnings, aspell for spelling, etc
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        aspell \
        aspell-en \
        libcanberra-gtk3-module \
        libtool-bin \
        xorg \
    && rm -rf /var/lib/apt/lists/*

# ripgrep variables
ARG RG_URL="https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb"
ARG RG_FILE="ripgrep_13.0.0_amd64.deb"
ARG RG_MD5SUM="83f105847a48c197916569cf72d8b0d3"

# Install ripgrep
RUN curl -fL -o $RG_FILE "$RG_URL" \
    && (echo "$RG_MD5SUM  $RG_FILE" | md5sum --quiet -c -) \
    && dpkg -i $RG_FILE \
    && rm -f $RG_FILE

# fd variables
ARG FD_URL="https://github.com/sharkdp/fd/releases/download/v8.2.1/fd_8.2.1_amd64.deb"
ARG FD_FILE="fd_8.2.1_amd64.deb"
ARG FD_MD5SUM="abcbae7ca319d219bd1a95997fd0250a"

# Install fd
RUN curl -fL -o $FD_FILE "$FD_URL" \
    && (echo "$FD_MD5SUM  $FD_FILE" | md5sum --quiet -c -) \
    && dpkg -i $FD_FILE \
    && rm -f $FD_FILE

# Switch to non-root user
USER $DEV_USER
WORKDIR $DEV_USER_HOME

# Doom Emacs variables
ARG DE_EMACS_DIR="/vols/emacs.d"
ARG DE_DOOM_DIR="/vols/doom.d"

# Straight makes heavy use of symlinks with absolute paths for its internal
# organization. Copying those symlinks will break them, unless the absolute
# paths stay the same. That is to say, $DE_EMACS_DIR must equal
# $EMACS_CONFIG_DIR, etc.
ENV EMACS_CONFIG_DIR="$DE_EMACS_DIR"
ENV DOOM_CONFIG_DIR="$DE_DOOM_DIR"

# Make blank directories to ensure permissions are set correctly
RUN sudo mkdir -m 755 $EMACS_CONFIG_DIR $DOOM_CONFIG_DIR \
    && sudo chown $DEV_USER:$DEV_USER $EMACS_CONFIG_DIR $DOOM_CONFIG_DIR

# Add links to the home directory
RUN ln -s $EMACS_CONFIG_DIR $DEV_USER_HOME/.emacs.d \
    && ln -s $DOOM_CONFIG_DIR $DEV_USER_HOME/.doom.d

# Copy files from the build layer
COPY --from=doom-cache --chown=$DEV_USER:$DEV_USER $DE_EMACS_DIR $EMACS_CONFIG_DIR
COPY --from=doom-cache --chown=$DEV_USER:$DEV_USER $DE_DOOM_DIR $DOOM_CONFIG_DIR

# Doom font variables
ARG DE_NERDFONT_URL="https://raw.githubusercontent.com/rainstormstudio/nerd-icons.el/main/fonts/NFM.ttf"
ARG DE_NERDFONT_FILE="$DEV_USER_HOME/.local/share/fonts/NFM.ttf"

# Update the font cache
RUN mkdir -p $(dirname $DE_NERDFONT_FILE) \
    && curl -fL -o $DE_NERDFONT_FILE "$DE_NERDFONT_URL" \
    && fc-cache -f

# Add Doom executables to PATH
ENV PATH=$EMACS_CONFIG_DIR/bin:$PATH

# Set environment variables used by Doom
ENV EMACSDIR=$DE_EMACS_DIR
ENV DOOMDIR=$DE_DOOM_DIR

# Build the VTerm module. We must locate the exact build directory because it's
# name depends on the Emacs version, e.g., `build-28.1`, etc.
RUN VTERM_BUILD_DIR=$(fd -uu -p "build-[0-9.]+/vterm$" $EMACS_CONFIG_DIR) \
    && cd $VTERM_BUILD_DIR \
    && cmake -S . -B build \
    && cmake --build build

# Add VTerm integration to Bash config
RUN { \
        echo; \
        echo "# When using VTerm, include the Bash integration"; \
        echo "if [ \"\${INSIDE_EMACS}\" = \"vterm\" \\"; \
        echo "      -a -n \"\${EMACS_VTERM_PATH}\" \\"; \
        echo "      -a -f \"\${EMACS_VTERM_PATH}/etc/emacs-vterm-bash.sh\" ]; then"; \
        echo "    source \"\${EMACS_VTERM_PATH}/etc/emacs-vterm-bash.sh\""; \
        echo "fi"; \
    } >> $DEV_USER_HOME/.bashrc

# Persistent storage for the Emacs and Doom config directories. These
# directories will be initialized with the Doom files from above.
VOLUME ["$EMACS_CONFIG_DIR", "$DOOM_CONFIG_DIR"]

# Copy the Emacs shim for the entry point
COPY emacs_shim.sh /emacs_shim.sh

# Launch Emacs by default
CMD ["/emacs_shim.sh", "/bin/bash"]
