# .github/workflows/build.yaml

# Copyright (c) 2025 Tim Perkins

name: Build Image

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
    branches:
      - main

env:
  TARGET_IMAGE: ghcr.io/taughz/dev
  EMACS_BUILDER_IMAGE: ghcr.io/taughz/dev-emacs-builder
  DOOM_CACHE_IMAGE: ghcr.io/taughz/dev-doom-cache

defaults:
  run:
    shell: bash

jobs:
  build_image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Determine Target Tag
        id: target_tag
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            tag=$(printf "pr-%d" "${{ github.event.pull_request.number }}")
          else
            tag=$(sed -e 's/[^A-Za-z0-9]\+/-/g' -e 's/^-\+//' <<< "${{ github.ref_name }}")
          fi
          echo "tag=$tag" >> $GITHUB_OUTPUT
      - name: Build Emacs Builder Image
        id: emacs_builder
        uses: taughz/hn2b@4bf6c223193412b9d004ba5ae94040c4558c7213
        with:
          image: ${{ env.EMACS_BUILDER_IMAGE }}:${{ steps.target_tag.outputs.tag }}
          context: containers/emacs/emacs_builder
          dockerfile: Containerfile
          skip-pull: true
          push: true
          registry-pass: ${{ secrets.REGISTRY_TOKEN }}
          cache-from: |
            type=registry,ref=${{ env.EMACS_BUILDER_IMAGE }}:${{ steps.target_tag.outputs.tag }}
            ${{ github.event_name == 'pull_request' && format('type=registry,ref={0}:main', env.EMACS_BUILDER_IMAGE) || '' }}
      - name: Build Doom Cache Image
        id: doom_cache
        uses: taughz/hn2b@4bf6c223193412b9d004ba5ae94040c4558c7213
        with:
          image: ${{ env.DOOM_CACHE_IMAGE }}:${{ steps.target_tag.outputs.tag }}
          context: containers/emacs/doom_cache
          dockerfile: Containerfile
          build-args: |
            EMACS_BUILDER_IMAGE=${{ steps.emacs_builder.outputs.image }}
          skip-pull: true
          push: true
          registry-pass: ${{ secrets.REGISTRY_TOKEN }}
          cache-from: |
            type=registry,ref=${{ env.DOOM_CACHE_IMAGE }}:${{ steps.target_tag.outputs.tag }}
            ${{ github.event_name == 'pull_request' && format('type=registry,ref={0}:main', env.DOOM_CACHE_IMAGE) || '' }}
      - name: Build Base Layer
        id: base
        uses: taughz/hn2b@4bf6c223193412b9d004ba5ae94040c4558c7213
        with:
          image: ${{ env.TARGET_IMAGE }}:${{ steps.target_tag.outputs.tag }}-base
          context: containers/base
          dockerfile: Containerfile
          skip-pull: true
          push: true
          registry-pass: ${{ secrets.REGISTRY_TOKEN }}
          cache-from: |
            type=registry,ref=${{ env.TARGET_IMAGE }}:${{ steps.target_tag.outputs.tag }}-base
            ${{ github.event_name == 'pull_request' && format('type=registry,ref={0}:main-base', env.TARGET_IMAGE) || '' }}
      - name: Build Agent Layer
        id: agent
        uses: taughz/hn2b@4bf6c223193412b9d004ba5ae94040c4558c7213
        with:
          image: ${{ env.TARGET_IMAGE }}:${{ steps.target_tag.outputs.tag }}-agent
          context: containers/agent
          dockerfile: Containerfile
          base-image: ${{ steps.base.outputs.image }}
          skip-pull: true
          push: true
          registry-pass: ${{ secrets.REGISTRY_TOKEN }}
          cache-from: |
            type=registry,ref=${{ env.TARGET_IMAGE }}:${{ steps.target_tag.outputs.tag }}-agent
            ${{ github.event_name == 'pull_request' && format('type=registry,ref={0}:main-agent', env.TARGET_IMAGE) || '' }}
      - name: Build C++ Layer
        id: cpp
        uses: taughz/hn2b@4bf6c223193412b9d004ba5ae94040c4558c7213
        with:
          image: ${{ env.TARGET_IMAGE }}:${{ steps.target_tag.outputs.tag }}-cpp
          context: containers/cpp
          dockerfile: Containerfile
          base-image: ${{ steps.agent.outputs.image }}
          skip-pull: true
          push: true
          registry-pass: ${{ secrets.REGISTRY_TOKEN }}
          cache-from: |
            type=registry,ref=${{ env.TARGET_IMAGE }}:${{ steps.target_tag.outputs.tag }}-cpp
            ${{ github.event_name == 'pull_request' && format('type=registry,ref={0}:main-cpp', env.TARGET_IMAGE) || '' }}
      - name: Build Python Layer
        id: python
        uses: taughz/hn2b@4bf6c223193412b9d004ba5ae94040c4558c7213
        with:
          image: ${{ env.TARGET_IMAGE }}:${{ steps.target_tag.outputs.tag }}-python
          context: containers/python
          dockerfile: Containerfile
          base-image: ${{ steps.cpp.outputs.image }}
          skip-pull: true
          push: true
          registry-pass: ${{ secrets.REGISTRY_TOKEN }}
          cache-from: |
            type=registry,ref=${{ env.TARGET_IMAGE }}:${{ steps.target_tag.outputs.tag }}-python
            ${{ github.event_name == 'pull_request' && format('type=registry,ref={0}:main-python', env.TARGET_IMAGE) || '' }}
      - name: Build ROS Layer
        id: ros
        uses: taughz/hn2b@4bf6c223193412b9d004ba5ae94040c4558c7213
        with:
          image: ${{ env.TARGET_IMAGE }}:${{ steps.target_tag.outputs.tag }}-ros
          context: containers/ros
          dockerfile: Containerfile
          base-image: ${{ steps.python.outputs.image }}
          skip-pull: true
          push: true
          registry-pass: ${{ secrets.REGISTRY_TOKEN }}
          cache-from: |
            type=registry,ref=${{ env.TARGET_IMAGE }}:${{ steps.target_tag.outputs.tag }}-ros
            ${{ github.event_name == 'pull_request' && format('type=registry,ref={0}:main-ros', env.TARGET_IMAGE) || '' }}
      - name: Build EMSDK Layer
        id: emsdk
        uses: taughz/hn2b@4bf6c223193412b9d004ba5ae94040c4558c7213
        with:
          image: ${{ env.TARGET_IMAGE }}:${{ steps.target_tag.outputs.tag }}-emsdk
          context: containers/emsdk
          dockerfile: Containerfile
          base-image: ${{ steps.ros.outputs.image }}
          skip-pull: true
          push: true
          registry-pass: ${{ secrets.REGISTRY_TOKEN }}
          cache-from: |
            type=registry,ref=${{ env.TARGET_IMAGE }}:${{ steps.target_tag.outputs.tag }}-emsdk
            ${{ github.event_name == 'pull_request' && format('type=registry,ref={0}:main-emsdk', env.TARGET_IMAGE) || '' }}
      - name: Build Emacs Layer
        id: emacs
        uses: taughz/hn2b@4bf6c223193412b9d004ba5ae94040c4558c7213
        with:
          image: ${{ env.TARGET_IMAGE }}:${{ steps.target_tag.outputs.tag }}
          context: containers/emacs
          dockerfile: Containerfile
          base-image: ${{ steps.emsdk.outputs.image }}
          build-args: |
            EMACS_BUILDER_IMAGE=${{ steps.emacs_builder.outputs.image }}
            DOOM_CACHE_IMAGE=${{ steps.doom_cache.outputs.image }}
          skip-pull: true
          push: true
          registry-pass: ${{ secrets.REGISTRY_TOKEN }}
          cache-from: |
            type=registry,ref=${{ env.TARGET_IMAGE }}:${{ steps.target_tag.outputs.tag }}
            ${{ github.event_name == 'pull_request' && format('type=registry,ref={0}:main', env.TARGET_IMAGE) || '' }}
      - name: Build Xpra Layer
        id: xpra
        uses: taughz/hn2b@4bf6c223193412b9d004ba5ae94040c4558c7213
        with:
          image: ${{ env.TARGET_IMAGE }}:${{ steps.target_tag.outputs.tag }}-xpra
          context: containers/xpra
          dockerfile: Containerfile
          base-image: ${{ steps.emacs.outputs.image }}
          skip-pull: true
          push: true
          registry-pass: ${{ secrets.REGISTRY_TOKEN }}
          cache-from: |
            type=registry,ref=${{ env.TARGET_IMAGE }}:${{ steps.target_tag.outputs.tag }}-xpra
            ${{ github.event_name == 'pull_request' && format('type=registry,ref={0}:main-xpra', env.TARGET_IMAGE) || '' }}
